// Catalog rows copied from the uploaded product seed and Talents Mapping guide.
// Formula config_data is intentionally a draft marker. Sample scoring keys are not copied.
// Activity cluster is null: the guide does not assign a cluster to every activity.
// ist formula_type is the name from the product doc; no norm rows are seeded.
// tech_js has no formula_type in the product pack.

export type MasterTestSeed = {
  code: string;
  name: string;
  category: string;
  description: string;
  instructions: string;
  duration_sec: number;
  total_questions: number;
  formula_type: string | null;
};

export const MASTER_TEST_SEEDS: MasterTestSeed[] = [
  {
    code: "wpt",
    name: "Wonderlic Personnel Test (WPT)",
    category: "COGNITIVE",
    description: "Tes kognitif dan logika penyelesaian masalah",
    instructions: "Jawablah pertanyaan berikut dengan cepat dan tepat dalam waktu 12 menit. Mohon tidak menggunakan alat bantu hitung apapun.",
    duration_sec: 720,
    total_questions: 50,
    formula_type: "wpt_correct_count",
  },
  {
    code: "ist",
    name: "Intelligenz Struktur Test (IST)",
    category: "COGNITIVE",
    description: "Tes struktur inteligensi verbal, numerik, dan spasial (9 subtes)",
    instructions: "Selesaikan sembilan subtes kemampuan berpikir dan inteligensi berikut. Setiap subtes memiliki batas waktu tersendiri.",
    duration_sec: 5400,
    total_questions: 176,
    formula_type: "ist_norms",
  },
  {
    code: "mbti",
    name: "Myers-Briggs Type Indicator (MBTI)",
    category: "PERSONALITY",
    description: "Identifikasi 16 tipe kepribadian Myers-Briggs",
    instructions: "Pilih salah satu pernyataan (A atau B) yang paling mencerminkan diri Anda secara jujur.",
    duration_sec: 900,
    total_questions: 93,
    formula_type: "mbti_bipolar",
  },
  {
    code: "disc",
    name: "DISC Personality Assessment",
    category: "PERSONALITY",
    description: "Asesmen 4 kuadran kepribadian dominan (D-I-S-C)",
    instructions: "Pilih satu pernyataan yang paling menggambarkan diri Anda (Paling) dan satu yang paling tidak menggambarkan diri Anda (Kurang) di lingkungan kerja.",
    duration_sec: 600,
    total_questions: 28,
    formula_type: "disc_most_least",
  },
  {
    code: "papi",
    name: "PAPI Kostick Personality",
    category: "PERSONALITY",
    description: "Asesmen kepribadian dan gaya perilaku kerja (20 aspek)",
    instructions: "Pilih salah satu dari sepasang pernyataan (A atau B) yang paling sesuai dengan diri Anda.",
    duration_sec: 900,
    total_questions: 90,
    formula_type: "papi_scale",
  },
  {
    code: "bigfive",
    name: "Big Five Personality (OCEAN)",
    category: "PERSONALITY",
    description: "Asesmen 5 faktor kepribadian utama (OCEAN)",
    instructions: "Pilih tingkat persetujuan Anda terhadap pernyataan berikut (skala 1-5).",
    duration_sec: 900,
    total_questions: 44,
    formula_type: "bigfive_matrix",
  },
  {
    code: "enneagram",
    name: "Enneagram Assessment",
    category: "PERSONALITY",
    description: "Asesmen 9 tipe kepribadian Enneagram dengan sayap (wing)",
    instructions: "Pilih tingkat kecocokan setiap pernyataan dengan diri Anda (skala 1-5).",
    duration_sec: 1200,
    total_questions: 180,
    formula_type: "enneagram_scale",
  },
  {
    code: "talents_mapping",
    name: "Talents Mapping® (34 Tema Bakat)",
    category: "PERSONALITY",
    description: "Asesmen 34 tema bakat CliftonStrengths + ST-30 + Potensi Kekuatan",
    instructions: "Bacalah setiap pernyataan dan pilih tingkat kesesuaiannya dengan diri Anda (skala 1-5). Jawab dengan jujur berdasarkan kondisi nyata, bukan ideal.",
    duration_sec: 2400,
    total_questions: 170,
    formula_type: "tm_rank_scale",
  },
  {
    code: "riasec",
    name: "Holland RIASEC Interest Test",
    category: "VOKASIONAL",
    description: "Tes minat karir dan vokasional Holland (6 tipe)",
    instructions: "Jawablah apakah Anda menyukai atau tidak menyukai aktivitas atau pekerjaan berikut.",
    duration_sec: 900,
    total_questions: 108,
    formula_type: "riasec_scale",
  },
  {
    code: "msdt",
    name: "Management Style Diagnostic Test",
    category: "LEADERSHIP",
    description: "Evaluasi 8 gaya kepemimpinan dan manajemen",
    instructions: "Pilih salah satu pernyataan (A atau B) yang paling sesuai dengan kecenderungan kepemimpinan Anda.",
    duration_sec: 1200,
    total_questions: 80,
    formula_type: "msdt_scale",
  },
  {
    code: "msai",
    name: "MSAI Assessment",
    category: "LEADERSHIP",
    description: "Management Skills Assessment Instrument (12 skill manajerial)",
    instructions: "Jawablah pertanyaan penilaian kemampuan manajerial berikut sesuai tingkat persetujuan Anda.",
    duration_sec: 1200,
    total_questions: 90,
    formula_type: "msai_scale",
  },
  {
    code: "tech_js",
    name: "Javascript & Node.js Developer Test",
    category: "TECHNICAL",
    description: "Tes teknikal pemrograman Javascript menengah-lanjut",
    instructions: "Jawablah pertanyaan teoritis dan berikan penjelasan konseptual singkat.",
    duration_sec: 1800,
    total_questions: 40,
    formula_type: null,
  },
];

export const TALENT_THEME_SEEDS = [
  { code: "ACH", name: "Achiever", domain: "Striving", description: "Stamina tinggi, bekerja keras, tidak pernah puas dengan hasil saat ini" },
  { code: "ACT", name: "Activator", domain: "Influencing", description: "Mengubah pikiran menjadi tindakan, tidak sabar untuk memulai" },
  { code: "ADA", name: "Adaptability", domain: "Relating", description: "Menyesuaikan diri dengan perubahan, hidup dalam momen saat ini" },
  { code: "ANA", name: "Analytical", domain: "Thinking", description: "Mencari alasan & sebab-musabab, butuh fakta dan bukti" },
  { code: "ARR", name: "Arranger", domain: "Executing", description: "Mengorganisir secara fleksibel, menemukan konfigurasi paling produktif" },
  { code: "BEL", name: "Belief", domain: "Striving", description: "Nilai-nilai luhur yang tidak berubah, senang melayani sebagai perbuatan mulia" },
  { code: "CMD", name: "Command", domain: "Influencing", description: "Senang menjadi penanggung jawab, berani konfrontasi, mengambil alih situasi" },
  { code: "COM", name: "Communication", domain: "Influencing", description: "Mudah mengungkapkan pikiran lewat kata-kata/tulisan yang mudah dimengerti" },
  { code: "CMP", name: "Competition", domain: "Striving", description: "Membandingkan diri dengan orang lain, selalu ingin menjadi nomor satu" },
  { code: "CON", name: "Connectedness", domain: "Relating", description: "Mengaitkan peristiwa satu dengan lainnya, percaya semua ada sebabnya" },
  { code: "CST", name: "Consistency", domain: "Executing", description: "Memperlakukan semua orang secara adil dan sama rata" },
  { code: "CTX", name: "Context", domain: "Thinking", description: "Memahami masa kini melalui riset dan studi masa lalu" },
  { code: "DEL", name: "Deliberative", domain: "Executing", description: "Berhati-hati, skeptis, melihat sebelum melompat" },
  { code: "DEV", name: "Developer", domain: "Relating", description: "Mengenali & menggali potensi orang lain, senang melihat kemajuan individu" },
  { code: "DIS", name: "Discipline", domain: "Executing", description: "Senang kondisi teratur, terstruktur, terencana, bersistem" },
  { code: "EMP", name: "Empathy", domain: "Relating", description: "Mampu merasakan perasaan orang lain seakan mengalaminya sendiri" },
  { code: "FOC", name: "Focus", domain: "Striving", description: "Butuh tujuan jelas sebagai kompas, menjaga prioritas dan jalur" },
  { code: "FUT", name: "Futuristic", domain: "Influencing", description: "Senang berangan-angan masa depan, memberi inspirasi dengan visi" },
  { code: "HAR", name: "Harmony", domain: "Relating", description: "Bekerja sama dengan baik, tidak suka konflik, mencari kesamaan" },
  { code: "IDE", name: "Ideation", domain: "Thinking", description: "Menyukai diskusi bebas, brainstorming, menemukan ide & koneksi baru" },
  { code: "INC", name: "Includer", domain: "Relating", description: "Menerima semua orang, memastikan semua merasa memiliki dalam kelompok" },
  { code: "IND", name: "Individualization", domain: "Relating", description: "Melihat keunikan masing-masing orang, memikirkan cara kerja sama produktif" },
  { code: "INP", name: "Input", domain: "Thinking", description: "Senang mengumpulkan & mengarsip informasi, ingin tahu segalanya" },
  { code: "INT", name: "Intellection", domain: "Thinking", description: "Senang berpikir mendalam, mawas diri, diskusi intelektual" },
  { code: "LRN", name: "Learner", domain: "Thinking", description: "Senang mempelajari sesuatu, tertarik pada proses belajar itu sendiri" },
  { code: "MAX", name: "Maximizer", domain: "Influencing", description: "Fokus pada kekuatan yang ada untuk merangsang keunggulan" },
  { code: "POS", name: "Positivity", domain: "Relating", description: "Antusiasme tinggi, optimisme menular, membuat orang bersemangat" },
  { code: "REL", name: "Relator", domain: "Relating", description: "Menikmati hubungan dekat/erat, kepuasan mendalam dari kerja bersama teman" },
  { code: "RES", name: "Responsibility", domain: "Executing", description: "Rasa tanggung jawab tinggi atas komitmen yang dibuat" },
  { code: "RST", name: "Restorative", domain: "Executing", description: "Senang memecahkan masalah, mengembalikan sesuatu menjadi berfungsi baik" },
  { code: "SAU", name: "Self-Assurance", domain: "Influencing", description: "Kepercayaan diri tinggi, inner compass kuat dalam membuat keputusan" },
  { code: "SIG", name: "Significance", domain: "Influencing", description: "Senang menjadi pusat perhatian, diakui atas keunikan dan keistimewaan" },
  { code: "STR", name: "Strategic", domain: "Thinking", description: "Memilah masalah dan menemukan jalan terbaik, melihat pola dari kekacauan" },
  { code: "WOO", name: "Woo", domain: "Influencing", description: "Senang bertemu orang baru dan menjadi akrab, memenangkan hati orang lain" },
];

export const STRENGTH_ACTIVITY_SEEDS = [
  { code: "ACTING", name: "ACTING", definition: "Mengekspresikan peran-peran berbeda dari keadaan diri sesungguhnya" },
  { code: "ADVERTISING", name: "ADVERTISING", definition: "Menampilkan produk/layanan/acara melalui media promosi" },
  { code: "ADVISING", name: "ADVISING", definition: "Memberikan nasihat atau saran kepada orang lain" },
  { code: "ANALYSING", name: "ANALYSING", definition: "Mengurai, membedakan, memilah sesuatu secara metodologis" },
  { code: "ANIMATING", name: "ANIMATING", definition: "Menghasilkan gambar bergerak dari gambar statis" },
  { code: "APPRAISING", name: "APPRAISING", definition: "Menaksir nilai atau harga dari sesuatu" },
  { code: "ASSEMBLING", name: "ASSEMBLING", definition: "Menyusun/merakit suku cadang menjadi satu kesatuan" },
  { code: "ASSISTING", name: "ASSISTING", definition: "Membantu menyelesaikan tugas sebagai sub-ordinat" },
  { code: "AUDITING", name: "AUDITING", definition: "Pemeriksaan dan ulasan terkait keuangan/prosedur/instalasi" },
  { code: "BEAUTIFYING", name: "BEAUTIFYING", definition: "Mengubah tampilan sesuatu menjadi lebih menarik" },
  { code: "BOOKEEPING", name: "BOOKEEPING", definition: "Mencatat transaksi keuangan dalam catatan berstandar" },
  { code: "BROKERING", name: "BROKERING", definition: "Menjadi penghubung antara kedua belah pihak untuk transaksi bisnis" },
  { code: "BUDGETING", name: "BUDGETING", definition: "Merencanakan, mengatur dan mengalokasikan anggaran" },
  { code: "BUILDING", name: "BUILDING", definition: "Membuat konstruksi rumah, gedung, jembatan, dan struktur lainnya" },
  { code: "CARING", name: "CARING", definition: "Menunjukkan perhatian dan kepedulian terhadap orang lain" },
  { code: "CASHIERING", name: "CASHIERING", definition: "Menerima, menyimpan, membayarkan uang sesuai prosedur" },
  { code: "COACHING", name: "COACHING", definition: "Bermitra untuk menemukan dan mengembangkan potensi kekuatan" },
  { code: "COLLECTING", name: "COLLECTING", definition: "Melakukan penagihan sesuai kontrak yang disepakati" },
  { code: "COMMUNICATING", name: "COMMUNICATING", definition: "Menyampaikan pikiran/perasaan sehingga orang lain mengerti" },
  { code: "COMPLIANCING", name: "COMPLIANCING", definition: "Menjalankan dan menjaga kepatuhan terhadap aturan" },
  { code: "CONCEPTUALIZING", name: "CONCEPTUALIZING", definition: "Membuat konsep sebagai pedoman masa depan" },
  { code: "CONSERVING", name: "CONSERVING", definition: "Menjaga sumber daya budaya dan lingkungan dari kerusakan" },
  { code: "CONSULTING", name: "CONSULTING", definition: "Memberikan arahan/strategi/solusi sesuai pengetahuan dan pengalaman" },
  { code: "CONTROLLING", name: "CONTROLLING", definition: "Menggunakan kekuasaan untuk mengatur dan mengawasi pelaksanaan tugas" },
  { code: "COOKING", name: "COOKING", definition: "Membuat dan memproduksi makanan/kuliner" },
  { code: "COOPERATING", name: "COOPERATING", definition: "Bekerjasama dengan orang lain untuk mencapai sasaran bersama" },
  { code: "COORDINATING", name: "COORDINATING", definition: "Mengatur pembagian tugas kepada beberapa orang" },
  { code: "CORRESPONDING", name: "CORRESPONDING", definition: "Berkomunikasi secara tertulis (surat, email, media sosial)" },
  { code: "COSTING", name: "COSTING", definition: "Memantau pengeluaran dana dalam pelaksanaan proyek" },
  { code: "COUNSELING", name: "COUNSELING", definition: "Membantu mencarikan solusi atas masalah pribadi/psikologis" },
  { code: "CREATING", name: "CREATING", definition: "Menggunakan imajinasi untuk menemukan rancangan/produk/layanan baru" },
  { code: "DANCING", name: "DANCING", definition: "Menampilkan gerakan tubuh yang indah dan harmonis" },
  { code: "DELIVERING", name: "DELIVERING", definition: "Mengirim sesuatu ke alamat atau orang tertentu" },
  { code: "DESIGNING", name: "DESIGNING", definition: "Membuat rancangan detail dari produk/sistem/bangunan" },
  { code: "DEVELOPING", name: "DEVELOPING", definition: "Mengubah sesuatu menjadi lebih baik, lebih kuat, lebih menarik" },
  { code: "DIAGNOSING", name: "DIAGNOSING", definition: "Mencari dan menemukan akar penyebab dari suatu masalah" },
  { code: "DISPATCHING", name: "DISPATCHING", definition: "Menugaskan seseorang ke tempat tertentu sesuai tugas" },
  { code: "DISTRIBUTING", name: "DISTRIBUTING", definition: "Mendistribusikan barang/dokumen/informasi ke beberapa tujuan" },
  { code: "DRAFTING", name: "DRAFTING", definition: "Membuat gambar teknik (blueprint, skema, diagram, denah)" },
  { code: "DRAMATIZING", name: "DRAMATIZING", definition: "Menjadikan suatu peristiwa lebih menarik/dramatis" },
  { code: "EDITING", name: "EDITING", definition: "Menyusun, merapikan, mengoreksi tulisan/audio/video sebelum dipublikasikan" },
  { code: "ENTERTAINING", name: "ENTERTAINING", definition: "Membuat seseorang atau sekelompok orang menjadi terhibur" },
  { code: "ESTIMATING", name: "ESTIMATING", definition: "Membuat perhitungan perkiraan biaya suatu pekerjaan" },
  { code: "EVALUATING", name: "EVALUATING", definition: "Menimbang atau menilai sesuatu untuk menentukan kualitas/kondisi" },
  { code: "FILING", name: "FILING", definition: "Menyimpan berkas/dokumen/file dengan rapi agar mudah ditemukan" },
  { code: "FINISHING", name: "FINISHING", definition: "Kegiatan sentuhan akhir dari proses produksi/proyek/konstruksi" },
  { code: "GREETING", name: "GREETING", definition: "Memberikan sapaan santun kepada orang lain" },
  { code: "GUIDING", name: "GUIDING", definition: "Membimbing orang lain menemukan sasaran atau jalan yang ditetapkan" },
  { code: "HOUSEKEEPING", name: "HOUSEKEEPING", definition: "Menyiapkan, merapikan, membersihkan sesuatu yang bersifat fisik/digital" },
  { code: "IDEATING", name: "IDEATING", definition: "Memiliki gagasan kreatif atas berbagai hal" },
  { code: "IDENTIFYING", name: "IDENTIFYING", definition: "Mengenali sesuatu atau seseorang untuk memastikan identitasnya" },
  { code: "INFLUENCING", name: "INFLUENCING", definition: "Mempengaruhi pikiran atau meyakinkan orang lain untuk mengikuti" },
  { code: "INFORMING", name: "INFORMING", definition: "Menyampaikan informasi, kabar, atau pengetahuan kepada orang lain" },
  { code: "INSPECTING", name: "INSPECTING", definition: "Memeriksa dengan teliti untuk memastikan kualitas/kebenaran" },
  { code: "INSTALLING", name: "INSTALLING", definition: "Menempatkan dan memasang sesuatu agar dapat beroperasi" },
  { code: "INTERPRETING", name: "INTERPRETING", definition: "Menjelaskan makna dengan bahasa yang mudah dimengerti" },
  { code: "INTERROGATING", name: "INTERROGATING", definition: "Mengajukan pertanyaan agresif untuk mengungkapkan kebenaran" },
  { code: "INTERVIEWING", name: "INTERVIEWING", definition: "Menggunakan teknik bertanya untuk mendapatkan informasi" },
  { code: "INVESTIGATING", name: "INVESTIGATING", definition: "Penyelidikan atau pencarian bukti dan fakta secara detail" },
  { code: "LIAISING", name: "LIAISING", definition: "Menjadi perwakilan organisasi untuk mengembangkan jaringan" },
  { code: "MAINTAINING", name: "MAINTAINING", definition: "Memelihara fungsi mesin, sistem, peralatan, atau bangunan" },
  { code: "MANUAL SKILL", name: "MANUAL SKILL", definition: "Pekerjaan yang banyak membutuhkan keterampilan tangan dan tubuh" },
  { code: "MARKETING", name: "MARKETING", definition: "Menyusun strategi pemasaran, menyajikan produk/layanan kepada publik" },
  { code: "MEDIATING", name: "MEDIATING", definition: "Upaya penyelesaian konflik atau perseteruan" },
  { code: "MENTORING", name: "MENTORING", definition: "Mengajarkan dengan cara memberikan contoh dan arahan" },
  { code: "MODELLING", name: "MODELLING", definition: "Kegiatan seorang model fashion" },
  { code: "MONITORING", name: "MONITORING", definition: "Mengawasi secara kontinyu kemungkinan ketidaksesuaian" },
  { code: "MOTIVATING", name: "MOTIVATING", definition: "Memberi semangat dan rasa optimis agar orang berkinerja maksimum" },
  { code: "MUSICAL ART", name: "MUSICAL ART", definition: "Kegiatan terkait seni musik (penggubah lagu, pemain alat musik)" },
  { code: "NEGOTIATING", name: "NEGOTIATING", definition: "Mendapatkan kesepakatan tentang hal yang belum diterima kedua pihak" },
  { code: "OBSERVING", name: "OBSERVING", definition: "Memperhatikan seseorang atau sesuatu dengan teliti, umumnya untuk ilmu" },
  { code: "OPERATING", name: "OPERATING", definition: "Menjalankan atau mengoperasikan mesin, peralatan, proses, atau sistem" },
  { code: "ORGANISING", name: "ORGANISING", definition: "Menyusun dan mengatur protokol kegiatan, sistem, benda, dan prosedur" },
  { code: "PHYSICAL SKILL", name: "PHYSICAL SKILL", definition: "Menggunakan koordinasi fisik (memanjat, mengontrol peralatan)" },
  { code: "PLANNING", name: "PLANNING", definition: "Membuat perencanaan, program dan prioritas kerja" },
  { code: "PLANTING", name: "PLANTING", definition: "Menyiapkan, menyemai, memelihara, merawat tumbuhan atau tanaman" },
  { code: "PRESENTING", name: "PRESENTING", definition: "Menyampaikan sesuatu kepada audiens dengan cara menarik dan mudah dimengerti" },
  { code: "PRODUCING", name: "PRODUCING", definition: "Membuat atau menghasilkan suatu barang atau karya" },
  { code: "PROGRAMMING", name: "PROGRAMMING", definition: "Merancang dan membuat program/antarmuka/piranti lunak berbasis komputer" },
  { code: "PUBLICIZING", name: "PUBLICIZING", definition: "Memberitakan atau mengumumkan sesuatu agar diketahui orang banyak" },
  { code: "PURCHASING", name: "PURCHASING", definition: "Membeli sesuatu untuk mendapatkan nilai ekonomis terbaik" },
  { code: "RECRUITING", name: "RECRUITING", definition: "Mencari, memilih, dan mempekerjakan seseorang untuk posisi tertentu" },
  { code: "REDACTING", name: "REDACTING", definition: "Memilih fokus pembahasan dan menyusun kembali dokumen tertulis" },
  { code: "RELATING", name: "RELATING", definition: "Menjalin hubungan persahabatan berdasarkan saling pengertian" },
  { code: "REPORTING", name: "REPORTING", definition: "Menyusun dan menyampaikan laporan lisan maupun tulisan" },
  { code: "REPRESENTING", name: "REPRESENTING", definition: "Bertindak atau berbicara atas nama orang/pihak lain" },
  { code: "RESEARCHING", name: "RESEARCHING", definition: "Penelitian terencana untuk menemukan fakta-fakta dan teori baru" },
  { code: "RESTORING", name: "RESTORING", definition: "Memperbaiki sesuatu agar kembali kepada kondisi semula" },
  { code: "REVIEWING", name: "REVIEWING", definition: "Mengulas sesuatu, mengupas kekurangan dan keunggulan" },
  { code: "SAFEKEEPING", name: "SAFEKEEPING", definition: "Menjaga keselamatan dari risiko kecelakaan atau bahaya" },
  { code: "SCHEDULING", name: "SCHEDULING", definition: "Menyusun jadwal tugas atau aktivitas dalam periode waktu tertentu" },
  { code: "SECURING", name: "SECURING", definition: "Menjaga aset dari risiko kehilangan dan kerusakan" },
  { code: "SELLING", name: "SELLING", definition: "Menjual produk atau jasa dengan meyakinkan orang lain untuk membeli" },
  { code: "SERVING", name: "SERVING", definition: "Melayani orang lain dengan tulus dan profesional" },
  { code: "SINGING", name: "SINGING", definition: "Bernyanyi di depan publik atau penonton" },
  { code: "SPIRITUALIZING", name: "SPIRITUALIZING", definition: "Aktivitas spiritual seperti kontemplasi dan introspeksi nilai-nilai kehidupan" },
  { code: "SPORT", name: "SPORT", definition: "Melakukan kegiatan olahraga tertentu dan berprestasi" },
  { code: "STRATEGIZING", name: "STRATEGIZING", definition: "Memilih dan menentukan solusi/jalan terbaik menuju sasaran" },
  { code: "SUPPORTING", name: "SUPPORTING", definition: "Mendukung orang/kelompok lain melaksanakan tugas secara optimal" },
  { code: "SURVEYING", name: "SURVEYING", definition: "Memperhatikan sesuatu/seseorang dengan seksama untuk laporan/opini" },
  { code: "SYNTHESIZING", name: "SYNTHESIZING", definition: "Mencari dan mengintegrasikan ide-ide menjadi sesuatu yang baru" },
  { code: "TEACHING", name: "TEACHING", definition: "Mengajar dan menyampaikan ilmu pengetahuan dengan cara mudah dipahami" },
  { code: "TENDING ANIMAL", name: "TENDING ANIMAL", definition: "Memberi makan, merawat, melatih, dan mengembangbiakkan binatang" },
  { code: "TESTING", name: "TESTING", definition: "Melakukan uji coba untuk memastikan kualitas/kinerja/keandalan" },
  { code: "THERAPIES", name: "THERAPIES", definition: "Menyembuhkan dan merehabilitasi fisik, mental, atau perilaku seseorang" },
  { code: "TRAINING", name: "TRAINING", definition: "Mengajari keterampilan/prosedur/metode untuk mengembangkan kemampuan" },
  { code: "TRANSCRIBING", name: "TRANSCRIBING", definition: "Menuliskan kembali ringkasan/rekaman/dikte ke dalam catatan jelas" },
  { code: "TRANSLATING", name: "TRANSLATING", definition: "Menerjemahkan pernyataan lisan atau tulisan ke bahasa lain" },
  { code: "TYPEWRITING", name: "TYPEWRITING", definition: "Pengetikan atau memasukkan data untuk menghasilkan dokumen" },
  { code: "VERIFYING", name: "VERIFYING", definition: "Membuktikan sesuatu untuk memastikan kebenaran/kesesuaian" },
  { code: "VISIONING", name: "VISIONING", definition: "Mengantisipasi masa depan secara bijak dan menentukan sasaran tepat" },
  { code: "VISUAL ART", name: "VISUAL ART", definition: "Kegiatan seni visual (melukis, desain grafis, membuat patung, menggambar)" },
  { code: "VOLUNTEERING", name: "VOLUNTEERING", definition: "Melakukan aktivitas sosial secara sukarela" },
  { code: "WRITING", name: "WRITING", definition: "Menulis artikel, ide, dokumen, cerita, blog, atau buku" },
];

export const STRENGTH_TYPOLOGY_SEEDS = [
  { code: "ADM", name: "Administrator", description: "Pola kerja terstruktur, terencana, rapih, menjunjung tanggung jawab & ketaatan" },
  { code: "AMB", name: "Ambassador", description: "Menjaga jejaring relasi, komunikasi positif, tanggung jawab tinggi" },
  { code: "ANA", name: "Analyst", description: "Menikmati analisa angka/data rumit, pola pikir terstruktur dan teliti" },
  { code: "ARR", name: "Arranger", description: "Mengatur sumber daya untuk hasil optimal, berani minta orang jalankan keputusan" },
  { code: "CAR", name: "Caretaker", description: "Sensitif merasakan perasaan orang lain, tergerak menolong, percaya setiap tindakan positif adalah tugas hidup" },
  { code: "CMD", name: "Commander", description: "Berpendirian teguh, berani konfrontasi, berani ambil alih tanggung jawab" },
  { code: "COM", name: "Communicator", description: "Menjelaskan yang biasa menjadi luar biasa, nyaman di tengah orang banyak" },
  { code: "CRE", name: "Creator", description: "Penuh ide-ide baru, wawasan luas, mudah menentukan jalan menuju impian" },
  { code: "DES", name: "Designer", description: "Ide kreatif dipadukan analisa, sistematis dalam memilah sumber inspirasi" },
  { code: "DIS", name: "Distributor", description: "Strategis, adaptif terhadap perubahan, tetap berpegang pada kaidah" },
  { code: "EDU", name: "Educator", description: "Sabar & telaten memberikan penjelasan/bimbingan sesuai karakteristik unik anak didik" },
  { code: "EVA", name: "Evaluator", description: "Sangat analitis, penuh ketelitian & kehati-hatian, nyaman dengan aturan dan jadwal jelas" },
  { code: "EXP", name: "Explorer", description: "Gemar mengumpulkan data/informasi, menganalisis secara teliti dan terstruktur" },
  { code: "INT", name: "Interpreter", description: "Suka memahami & menganalisa informasi rumit, menjelaskan dengan cara mudah dimengerti" },
  { code: "JOU", name: "Journalist", description: "Cekatan menyampaikan informasi faktual secara jelas, menarik, dan kreatif" },
  { code: "MAR", name: "Marketer", description: "Berpikiran strategis & penuh ide, menjelaskan dengan cara sangat menarik" },
  { code: "MED", name: "Mediator", description: "Berani konfrontasi demi menyelesaikan konflik, wawasan luas dalam menjelaskan sumber masalah" },
  { code: "MOT", name: "Motivator", description: "Mendorong orang maju dan berkembang, mengenali potensi kekuatan masing-masing orang" },
  { code: "OPE", name: "Operator", description: "Nyaman mengikuti SOP yang jelas, pekerja keras, fleksibel menyesuaikan diri" },
  { code: "PRO", name: "Producer", description: "Dorongan kuat menghasilkan karya sempurna, menata ide dalam struktur jelas" },
  { code: "QCA", name: "Quality Controller", description: "Menjunjung tinggi prosedur/aturan, teliti, fiksasi pada kesempurnaan hasil kerja" },
  { code: "RES", name: "Restorer", description: "Dorongan natural memperbaiki segala sesuatu (manusia, perangkat, sistem)" },
  { code: "SAF", name: "Safekeeper", description: "Sistematis, taat aturan, tingkat kewaspadaan & kehati-hatian tinggi" },
  { code: "SLC", name: "Selector", description: "Dapat melihat keunikan sifat orang lain secara insting, menggali informasi sebelum menentukan pilihan" },
  { code: "SEL", name: "Seller", description: "Senang menyapa & meyakinkan orang tentang keunggulan produk/jasa" },
  { code: "SER", name: "Server", description: "Jiwa pelayanan tinggi, selalu tergerak menolong, mengedepankan kepentingan orang lain" },
  { code: "STR", name: "Strategist", description: "Insting baik memilih jalan paling tepat, keputusan didukung kajian objektif dan terstruktur" },
  { code: "SYN", name: "Synthesizer", description: "Mengumpulkan berbagai ide, menganalisa, menatanya menjadi ide yang sama sekali baru" },
  { code: "TRE", name: "Treasurer", description: "Logis dan analitis, mengutamakan ketelitian, senang mengatur sumber daya" },
  { code: "VIS", name: "Visionary", description: "Melihat jauh ke depan secara insting/intuisi, pemimpi yang tidak nyaman dengan batasan" },
];

